### ISSUE TITLE
Error when using object_tracker.py

### ISSUE THREAD

**Issue by rlimaboldmss** [theAIGuysCode/yolov3_deepsort#12]
Hi on my virtual environment with all dependencies required by requirements-gpu.txt when I run object_tracker.py I got this error

python object_tracker.py --video ./data/video/test.mp4 --output ./data/video/results.avi --weights ./weights/yolov3-tiny.tf --tiny
2020-05-12 03:11:30.555970: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-12 03:11:30.574436: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-12 03:11:30.575043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2060 SUPER computeCapability: 7.5
coreClock: 1.68GHz coreCount: 34 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 417.29GiB/s
2020-05-12 03:11:30.575142: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.2/lib64
2020-05-12 03:11:30.576358: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-05-12 03:11:30.577462: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-05-12 03:11:30.577653: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-05-12 03:11:30.578887: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-05-12 03:11:30.579652: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-05-12 03:11:30.582240: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-12 03:11:30.582269: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-05-12 03:11:30.583396: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-12 03:11:30.608803: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3398735000 Hz
2020-05-12 03:11:30.609290: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f72d8000b60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-12 03:11:30.609314: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-12 03:11:30.611123: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-12 03:11:30.611140: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      
Traceback (most recent call last):
  File "object_tracker.py", line 163, in <module>
    app.run(main)
  File "/home/servinfo/.virtualenvs/conda/lib/python3.8/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/servinfo/.virtualenvs/conda/lib/python3.8/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "object_tracker.py", line 41, in main
    encoder = gdet.create_box_encoder(model_filename, batch_size=1)
  File "/home/servinfo/yolov3_deepsort/tools/generate_detections.py", line 103, in create_box_encoder
    image_encoder = ImageEncoder(model_filename, input_name, output_name)
  File "/home/servinfo/yolov3_deepsort/tools/generate_detections.py", line 83, in __init__
    self.input_var = tf.get_default_graph().get_tensor_by_name(
  File "/home/servinfo/.virtualenvs/conda/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3688, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/servinfo/.virtualenvs/conda/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3512, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/servinfo/.virtualenvs/conda/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3552, in _as_graph_element_locked
    raise KeyError("The name %s refers to a Tensor which does not "
KeyError: "The name 'net/images:0' refers to a Tensor which does not exist. The operation, 'net/images', does not exist in the graph."
(tracker-gpu) (conda) servinfo@servinfo-desktop:~/yolov3_deepsort$ 

Can you help me?
BR

**Comment by Ahsanr312** [comment]
Have you set up the Nvidia driver? If not then install nvidia-driver-430.
Hope this helps

**Comment by aafaqin** [comment]
I am also getting the same error but when I copy everything on  google-colab it works perfectly file!

**Comment by Ahsanr312** [comment]
Yes, exact version would work. I personally use Colab for computing so it worked fine.

**Comment by kalthwaini** [comment]
Im having the same issue, and i rea your comment. would please explain more why i need nvidia-driver-430? why not using the one recommended from nvidia? (forgive me if its a dum question)

**Comment by Ahsanr312** [comment]
No, it's fine. Basically, I have followed exactly what this repository is directing for and used Google Colab. My advice is to follow exactly what this repository has mentioned. Are you using Colab?

**Comment by jacobsmith575161** [comment]
@Ahsanr312  I also need help with steps in realtion with Colab

**Comment by Ahsanr312** [comment]
@jacobsmith575161 What sort of help do you need?

**Comment by OSSome01** [comment]
my driver version is 440.44. is it okay or should i go back to 430
