### ISSUE TITLE
AttributeError: type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by 12343954** [theAIGuysCode/yolov3_deepsort#28]
always error. which version didi you install?  tensorflow-gpu, python, h5py , 
can you show out the `conda list` ? thank you!

```
(tracker-gpu) D:\yolov3_deepsort-master>python object_tracker.py --video 0 --output ./output/video_custom.avi --weights ./weights/yolov3-custom.tf --num_classes 11 --classes ./model_data/coco_custom.names
2020-09-13 17:56:28.603017: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "object_tracker.py", line 7, in <module>
    import tensorflow as tf
  File "D:\Programs\Anaconda3\envs\tracker-gpu\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\Programs\Anaconda3\envs\tracker-gpu\lib\site-packages\tensorflow\python\__init__.py", line 84, in <module>
    from tensorflow.python import keras
  File "D:\Programs\Anaconda3\envs\tracker-gpu\lib\site-packages\tensorflow\python\keras\__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "D:\Programs\Anaconda3\envs\tracker-gpu\lib\site-packages\tensorflow\python\keras\models.py", line 26, in <module>
    from tensorflow.python.keras.engine import network
  File "D:\Programs\Anaconda3\envs\tracker-gpu\lib\site-packages\tensorflow\python\keras\engine\network.py", line 47, in <module>
    from tensorflow.python.keras.saving import hdf5_format
  File "D:\Programs\Anaconda3\envs\tracker-gpu\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 41, in <module>
    import h5py
  File "D:\Programs\Anaconda3\envs\tracker-gpu\lib\site-packages\h5py\__init__.py", line 34, in <module>
    from . import version
  File "D:\Programs\Anaconda3\envs\tracker-gpu\lib\site-packages\h5py\version.py", line 17, in <module>
    from . import h5 as _h5
  File "h5py\h5.pyx", line 41, in init h5py.h5
AttributeError: type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'
```

```
(tracker-gpu) D:\yolov3_deepsort-master>conda list
# packages in environment at D:\Programs\Anaconda3\envs\tracker-gpu:
#
# Name                    Version                   Build  Channel
absl-py                   0.10.0                   pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
blas                      1.0                         mkl
ca-certificates           2020.7.22                     0
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.6.20                pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
cudatoolkit               10.1.243             h74a9793_0
cudnn                     7.6.5                cuda10.1_0
cycler                    0.10.0                   py37_0
cython                    0.29.21                  pypi_0    pypi
freetype                  2.10.2               hd328e21_0
gast                      0.2.2                    pypi_0    pypi
google-auth               1.21.1                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.32.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hdf5                      1.8.20               hac2f561_1
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10                     pypi_0    pypi
importlib-metadata        1.7.0                    pypi_0    pypi
intel-openmp              2020.2                      254
jpeg                      9b                   hb83a4c4_2
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.2.0            py37h74a9793_0
libopencv                 3.4.2                h20b85fd_0
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.1.0                h56a325e_1
lxml                      4.5.2                    pypi_0    pypi
lz4-c                     1.9.2                h62dcd97_1
markdown                  3.2.2                    pypi_0    pypi
matplotlib                3.2.2                         0
matplotlib-base           3.2.2            py37h64f37c6_0
mkl                       2020.2                      256
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.1.0            py37h45dec08_0
mkl_random                1.1.1            py37h47e9c7a_0
numpy                     1.18.5                   pypi_0    pypi
numpy-base                1.19.1           py37ha3acd2a_0
oauthlib                  3.1.0                    pypi_0    pypi
opencv                    3.4.2            py37h40b0b35_0
openssl                   1.1.1g               he774522_1
opt-einsum                3.3.0                    pypi_0    pypi
pandas                    1.1.2                    pypi_0    pypi
pip                       20.2.2                   py37_0
protobuf                  3.13.0                   pypi_0    pypi
py-opencv                 3.4.2            py37hc319ecb_0
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py37h6538335_2
python                    3.7.4                h5263a28_0
python-dateutil           2.8.1                      py_0
pytz                      2020.1                   pypi_0    pypi
qt                        5.9.7            vc14h73c81de_0
requests                  2.24.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.6                      pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
seaborn                   0.11.0                   pypi_0    pypi
setuptools                50.3.0                   pypi_0    pypi
sip                       4.19.8           py37h6538335_0
six                       1.15.0                     py_0
sqlite                    3.33.0               h2a8f88b_0
tensorboard               2.1.1                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow-gpu            2.2.0                    pypi_0    pypi
tensorflow-gpu-estimator  2.2.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tornado                   6.0.4            py37he774522_1
tqdm                      4.49.0                   pypi_0    pypi
urllib3                   1.25.10                  pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.35.1                   pypi_0    pypi
wincertstore              0.2                      py37_0
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h62dcd97_0
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.5                h04227a9_0

```

**Comment by Aarlington** [comment]
This should do the trick: `pip install h5py==2.9`

**Comment by 12343954** [comment]
Thank you but i give up TF.

**Comment by swaranlata-99** [comment]
(mypython3version) C:\Users\hp>conda list
# packages in environment at C:\Users\hp\anaconda3\envs\mypython3version:
#
# Name                    Version                   Build  Channel
absl-py                   0.12.0                   pypi_0    pypi
altgraph                  0.17                     pypi_0    pypi
argon2-cffi               20.1.0                   pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
blas                      1.0                         mkl
bleach                    3.3.0                    pypi_0    pypi
ca-certificates           2020.10.14                    0    anaconda
cachetools                4.2.2                    pypi_0    pypi
certifi                   2020.6.20                py38_0    anaconda
cffi                      1.14.5                   pypi_0    pypi
chardet                   4.0.0                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
decorator                 5.0.9                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
google-auth               1.31.0                   pypi_0    pypi
google-auth-oauthlib      0.4.4                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.34.1                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
hdf5                      1.10.4               h7ebc959_0    anaconda
icc_rt                    2019.0.0             h0cc432a_1    anaconda
idna                      2.10                     pypi_0    pypi
intel-openmp              2021.2.0           haa95532_616
ipykernel                 5.5.5                    pypi_0    pypi
ipython                   7.24.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.6.3                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    3.0.1                    pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.12                   pypi_0    pypi
jupyter-console           6.4.0                    pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-widgets        1.0.0                    pypi_0    pypi
keras                     2.4.3                    pypi_0    pypi
keras-nightly             2.5.0.dev2021032900          pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.4.2                    pypi_0    pypi
matplotlib-inline         0.1.2                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2021.2.0           haa95532_296
mkl-service               2.3.0            py38h2bbff1b_1
mkl_fft                   1.3.0            py38h277e83a_2
mkl_random                1.2.1            py38hf11a4ad_2
nbclient                  0.5.3                    pypi_0    pypi
nbconvert                 6.0.7                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
nest-asyncio              1.5.1                    pypi_0    pypi
notebook                  6.4.0                    pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
openssl                   1.1.1k               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.4                    pypi_0    pypi
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
pefile                    2021.5.24                pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.2.0                    pypi_0    pypi
pip                       21.0.1           py38haa95532_0
prometheus-client         0.11.0                   pypi_0    pypi
prompt-toolkit            3.0.18                   pypi_0    pypi
protobuf                  3.17.3                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pygments                  2.9.0                    pypi_0    pypi
pyinstaller               5.0.dev0                 pypi_0    pypi
pyinstaller-hooks-contrib 2021.1                   pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyreadline                2.1                      py38_1    anaconda
pyrsistent                0.17.3                   pypi_0    pypi
python                    3.8.8                hdbf39b2_5
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pywin32                   301                      pypi_0    pypi
pywin32-ctypes            0.2.0                    pypi_0    pypi
pywinpty                  1.1.2                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.1.0                   pypi_0    pypi
qtconsole                 5.1.0                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
scipy                     1.6.3                    pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
setuptools                52.0.0           py38haa95532_0
six                       1.15.0           py38haa95532_0
sqlite                    3.35.4               h2bbff1b_0
tensorboard               2.5.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.5.0                    pypi_0    pypi
tensorflow-estimator      2.5.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.10.1                   pypi_0    pypi
testpath                  0.5.0                    pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.5                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0
widgetsnbextension        3.5.1                    pypi_0    pypi
wincertstore              0.2                      py38_0
wrapt                     1.12.1                   pypi_0    pypi
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]  anaconda

**Comment by swaranlata-99** [comment]
AttributeError                            Traceback (most recent call last)
<ipython-input-19-69667bf45035> in <module>
----> 1 import tensorflow as tf
      2 from keras.preprocessing.image import ImageDataGenerator

~\anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

~\anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     45 from tensorflow.python import data
     46 from tensorflow.python import distribute
---> 47 from tensorflow.python import keras
     48 from tensorflow.python.feature_column import feature_column_lib as feature_column
     49 from tensorflow.python.layers import layers

~\anaconda3\lib\site-packages\tensorflow\python\keras\__init__.py in <module>
     25 
     26 # See b/110718070#comment18 for more details about this import.
---> 27 from tensorflow.python.keras import models
     28 
     29 from tensorflow.python.keras.engine.input_layer import Input

~\anaconda3\lib\site-packages\tensorflow\python\keras\models.py in <module>
     24 from tensorflow.python.keras import metrics as metrics_module
     25 from tensorflow.python.keras import optimizers
---> 26 from tensorflow.python.keras.engine import functional
     27 from tensorflow.python.keras.engine import sequential
     28 from tensorflow.python.keras.engine import training

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\functional.py in <module>
     36 from tensorflow.python.keras.engine import keras_tensor
     37 from tensorflow.python.keras.engine import node as node_module
---> 38 from tensorflow.python.keras.engine import training as training_lib
     39 from tensorflow.python.keras.engine import training_utils
     40 from tensorflow.python.keras.saving.saved_model import network_serialization

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in <module>
     51 from tensorflow.python.keras.engine import training_utils
     52 from tensorflow.python.keras.mixed_precision.experimental import loss_scale_optimizer as lso
---> 53 from tensorflow.python.keras.saving import hdf5_format
     54 from tensorflow.python.keras.saving import save
     55 from tensorflow.python.keras.saving.saved_model import model_serialization

~\anaconda3\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py in <module>
     39 # pylint: disable=g-import-not-at-top
     40 try:
---> 41   import h5py
     42   HDF5_OBJECT_HEADER_LIMIT = 64512
     43 except ImportError:

~\anaconda3\lib\site-packages\h5py\__init__.py in <module>
     32         raise
     33 
---> 34 from . import version
     35 
     36 if version.hdf5_version_tuple != version.hdf5_built_version_tuple:

~\anaconda3\lib\site-packages\h5py\version.py in <module>
     15 
     16 from collections import namedtuple
---> 17 from . import h5 as _h5
     18 import sys
     19 import numpy

h5py\h5.pyx in init h5py.h5()

AttributeError: type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'

**Comment by swaranlata-99** [comment]
sir how can sort out this issue i also provided 'conda list'

**Comment by markus-brln** [comment]
> 
> 
> sir how can sort out this issue i also provided 'conda list'



> 
> 
> This should do the trick: `pip install h5py==2.9`

Update for tensorflow 2.5.0:  `pip install h5py==3.1.0`

**Comment by salem-med** [comment]
Update for tensorflow 2.6.0: pip install --upgrade h5py

**Comment by sndnshr** [comment]
> This should do the trick: `pip install h5py==2.9`

works for tensorflow 1.14
