### ISSUE TITLE
Error during execution

### ISSUE THREAD

**Issue by conect** [theAIGuysCode/yolov3_deepsort#5]
after executing: 
python object_tracker.py --video 0 --output ./data/video/results.avi

I get following error:

Traceback (most recent call last):
  File "object_tracker.py", line 163, in <module>
    app.run(main)
  File "/home/machine/miniconda3/envs/tracker-gpu/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/machine/miniconda3/envs/tracker-gpu/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "object_tracker.py", line 155, in main
    if FLAGS.ouput:
  File "/home/machine/miniconda3/envs/tracker-gpu/lib/python3.7/site-packages/absl/flags/_flagvalues.py", line 473, in __getattr__
    raise AttributeError(name)
AttributeError: ouput

**Comment by conect** [comment]
Any hint? Thanks very much...

**Comment by theAIGuysCode** [comment]
This seems like an issue with the absl package that was downloaded. Attribute error "ouput" looks like  a type for output.

**Comment by conect** [comment]
How can I fix it?

**Comment by aguirrejuan** [comment]
> How can I fix it?

did you can to solve ?

**Comment by aguirrejuan** [comment]
HI,there is an error with the writing of the word, it is not "ouput" it is "output" you have to change it so that it works, thanks for your code the AI Guys Code
