### ISSUE TITLE
Getting error in encoder = gdet.create_box_encoder(model_filename, batch_size=1)

### ISSUE THREAD

**Issue by Teezq** [theAIGuysCode/yolov3_deepsort#53]
Hi theAIGuysCode, I have executed the object_tracker.py with all video parameters changed to my own video. However, I am getting the errors below:
Traceback (most recent call last):
  File "C:\Users\teezq\PycharmProjects\RTHDCS(FYP)\RTHDCS.py", line 57, in <module>
    encoder = gdet.create_box_encoder(model_filename, batch_size=1)
  File "C:\Users\teezq\PycharmProjects\RTHDCS(FYP)\tools\generate_detections.py", line 100, in create_box_encoder
    image_encoder = ImageEncoder(model_filename, input_name, output_name)
  File "C:\Users\teezq\PycharmProjects\RTHDCS(FYP)\tools\generate_detections.py", line 80, in init
    self.input_var = tf.get_default_graph().get_tensor_by_name(
  File "C:\Users\teezq\PycharmProjects\RTHDCS(FYP)\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3931, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "C:\Users\teezq\PycharmProjects\RTHDCS(FYP)\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3755, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Users\teezq\PycharmProjects\RTHDCS(FYP)\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 3795, in _as_graph_element_locked
    raise KeyError("The name %s refers to a Tensor which does not "
KeyError: "The name 'net/images:0' refers to a Tensor which does not exist. The operation, 'net/images', does not exist in the graph."

Does anyone got any hint what is causing this error.
I have ensure all the parameters are correct at the line: encoder = gdet.create_box_encoder(model_filename, batch_size=1). Moreover, I have redownloaded and replaced the "generate_detections.py" file multiple times.
Hoping to hear from your theAIGuysCode, I have really been working out on this error.

**Comment by Teezq** [comment]
This has been solved after looking other issue sessions. Thank you so much

**Comment by Amarnath911** [comment]
How you solve this issue? pls tell ...i need to resolve it urgent.Tq.

**Comment by Amarnath911** [comment]
> How you solve this issue? pls tell ...i need to resolve it urgent.Tq.

**Comment by LavanyaLahariRajaratnam** [comment]
I got same error, Can you please solve the issue.
