### ISSUE TITLE
Am having trouble making Gui when import preprocess_image as pi . The output error is ModuleNotFoundError: No module named 'preprocess_image' 

### ISSUE THREAD

**Issue by Duncan1738** [theAIGuysCode/yolov3_deepsort#56]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Anaconda\envs\tensorflowbackend\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "<ipython-input-5-11f9debb551a>", line 2, in submit
    import preprocessing_image as pi
ModuleNotFoundError: No module named ['preprocessing_image']
![Capture PNG111](https://user-images.githubusercontent.com/63037127/127115568-e3e674fe-d17c-4f69-8dae-a1c84f48d341.PNG)

**Comment by Duncan1738** [comment]
this is the output
![Capture PNG22](https://user-images.githubusercontent.com/63037127/127115980-953abb3d-9889-4ad4-96e7-5b4be0b82c0f.PNG)
