### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by queen25d** [theAIGuysCode/yolov3_deepsort#80]
C:\Users\Lenovo\anaconda3\envs\Noor\python.exe D:/PycharmProjects/pythonProject8/main.py
Traceback (most recent call last):
  File "D:/PycharmProjects/pythonProject8/main.py", line 25, in <module>
    from keras.models import Model
  File "C:\Users\Lenovo\anaconda3\envs\Noor\lib\site-packages\keras\models\__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "C:\Users\Lenovo\anaconda3\envs\Noor\lib\site-packages\keras\engine\functional.py", line 24, in <module>
    import tensorflow.compat.v2 as tf
  File "C:\Users\Lenovo\anaconda3\envs\Noor\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Lenovo\anaconda3\envs\Noor\lib\site-packages\tensorflow\python\__init__.py", line 47, in <module>
    from tensorflow.python import keras
  File "C:\Users\Lenovo\anaconda3\envs\Noor\lib\site-packages\tensorflow\python\keras\__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "C:\Users\Lenovo\anaconda3\envs\Noor\lib\site-packages\tensorflow\python\keras\models.py", line 26, in <module>
    from tensorflow.python.keras.engine import functional
  File "C:\Users\Lenovo\anaconda3\envs\Noor\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 38, in <module>
    from tensorflow.python.keras.engine import training as training_lib
  File "C:\Users\Lenovo\anaconda3\envs\Noor\lib\site-packages\tensorflow\python\keras\engine\training.py", line 53, in <module>
    from tensorflow.python.keras.saving import hdf5_format
  File "C:\Users\Lenovo\anaconda3\envs\Noor\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 41, in <module>
    import h5py
  File "C:\Users\Lenovo\anaconda3\envs\Noor\lib\site-packages\h5py\__init__.py", line 34, in <module>
    from . import version
  File "C:\Users\Lenovo\anaconda3\envs\Noor\lib\site-packages\h5py\version.py", line 17, in <module>
    from . import h5 as _h5
  File "h5py\h5.pyx", line 41, in init h5py.h5
AttributeError: type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'

**Comment by PalmaLuv** [comment]
Check if libraries are installed
```bash
# TensorFlow CPU
pip install -r requirements.txt

# TensorFlow GPU
pip install -r requirements-gpu.txt
```

Link to file : 
- [requirements.txt](https://github.com/theAIGuysCode/yolov3_deepsort/blob/master/requirements.txt)
- [requirements-gpu.txt](https://github.com/theAIGuysCode/yolov3_deepsort/blob/master/requirements-gpu.txt)

Or try downgrading your Python version
